- .github/workflows/main.yml
- .github/workflows/publish.yml
- .gitignore
- .jujuignore
- CONTRIBUTING.md
- LICENSE
- README.md
- actions.yaml
- charmcraft.yaml
- config.yaml
- icon.svg
- lib/charms/observability_libs/v0/kubernetes_service_patch.py
- lib/charms/tls_certificates_interface/v0/tls_certificates.py
- metadata.yaml
- pyproject.toml
- requirements.txt
- src/charm.py
- src/charm_policy.hcl
- src/vault.py
- tests/integration/kubernetes.py
- tests/integration/test_integration.py
- tests/integration/vault.py
- tests/unit/test_charm.py
- tests/unit/test_vault.py
- tox.ini
Implementation of the vault-k8s charm. Most of this project has been taken from @ChrisMacNaughton 's personnal project and improved with the intention of making it a more solid implementation, adding contributors, enabling better support and adding continuous integration.
This charm supports the tls-certificates relation through the tls-certificates-interface [library](https://github.com/canonical/tls-certificates-interface/pull/1) . 
References:
- Initial [charm](https://github.com/ChrisMacNaughton/charm-vault-k8s) from Chris
> Implementation of the vault-k8s charm

- .github/ISSUE_TEMPLATE/bug_report.md
> Adds bug report template

- .github/workflows/publish.yml
> Uses charming-actions 2.0.0

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
Bumps the tls-certificates lib version.
> Bumps the tls-certificates lib version

- .github/workflows/publish.yml
Bumps charm publishing action to latest version
> Bumps charm publishing action to latest version

- .github/workflows/main.yml
- charmcraft.yaml
- tox.ini
Archive charmcraft and juju logs on integration tests failure
> Archive logs on integration tests failure

- CODEOWNERS
Adds CODEOWNER file so that Telco team is noticed whenever there are changes in the project.
> Adds CODEOWNER

- renovate.json
> [Chore] Adds renovate file

- metadata.yaml
Bumps vault version to latest/stable release.
> [Chore] Bumps vault version to latest/stable release

- .github/workflows/integration-test.yaml
- .github/workflows/lint-report.yaml
- .github/workflows/main.yaml
- .github/workflows/publish-charm.yaml
- .github/workflows/static-analysis.yaml
- .github/workflows/unit-test.yaml
This PR decomposes the .github workflows main.yaml into separate logical sections, build the charm once and publish it if integration tests passed.
> Decompose github workflow items into separate files

- .github/workflows/publish-charm.yaml
Fixes error with Charmcraft secret introduced in previous PR. This fix should resolve the charm publishing that currently crashes in main.
> [Bugfix] Fixes error with Charmcraft secret introduced in previous PR

- CONTRIBUTING.md
- LICENSE
- README.md
- metadata.yaml
Improvements to project documentation.
> [Feat] Improves project documentation

- metadata.yaml
Fixups of a couple things I noticed while I was browsing on by
> Add display name, remove shebang

- src/charm.py
- src/vault.py
- tests/unit/test_charm.py
- tests/unit/test_vault.py
This PR will remove warnings when the Vault client is used to communicate with Vault.
> [feat] Uses CA certificate when initialising Vault client

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/workflows/issues.yaml
- Adds the issues workflow to sync github issues to JIRA
- Updates the Issues template
> Adds issues workflow

- README.md
- metadata.yaml
> chore: Bumps image version

- metadata.yaml
- src/charm.py
Mounts storage for /tmp in the container
> Mounts storage for /tmp in the container

- .github/workflows/lint-pr.yaml
Adds semantic PR name validation using this project: https://github.com/amannn/action-semantic-pull-request/tree/v5/
> chore: Adds semantic PR name validation

- README.md
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/traefik_k8s/v1/ingress.py
- lib/charms/traefik_k8s/v2/ingress.py
- metadata.yaml
- src/charm.py
- test-requirements.txt
- tests/integration/test_integration.py
- tests/unit/test_charm.py
This PR adds integration to Ingress. This includes:
-  Adding the ingress relation
-  Improving documentation
-  Adding integration to ingress in integration tests
-  Bump tls_certificates_interface library version
> feat: Integrate with Ingress

- requirements.txt
- src/charm.py
Bumps ops version and removes now unnecessary ignore statement.
> chore: Bumps ops version

- README.md
- metadata.yaml
Bumps vault ROCK version to 1.15.2
> feat: Bumps vault ROCK version to 1.15.2

- .gitignore
This file is copied to this location by the integration tests, and should not be committed.
> chore: Add copied file to gitignore

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/traefik_k8s/v2/ingress.py
Uses the latest version of the charm libraries simply by running `charmcraft fetch-lib`.
> chore: Bumps the charm libraries

- src/charm.py
- src/s3_session.py
- tests/unit/test_charm.py
Handles time out error when connecting to s3 endpoint and adds unit test cases.
We configure boto3 to try only once to connect to the endpoint and raise if that fails, the the actions will output a message indicating the failure to connect to the endpoint, this is to give faster feedback to the user in case of misconfiguring the S3 endpoint.
> fix: Handles time out error when connecting to s3 endpoint

- .gitignore
> chore: Ignore tox generated files

- lib/charms/vault_k8s/v0/vault_tls.py
- src/container.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm.py
Adds a few fixes:
- Adds stop function in WorkloadBase
- Refactors `_set_ca_certificate_secret_in_peer_relation` in the test
> fix: Extends the interface of WorkloadBase.

- README.md
- metadata.yaml
Bump Vault OCI image to v1.15.5
> chore: bump vault to v1.15.5

- .github/workflows/integration-test.yaml
> chore: bump microk8s to v1.29

- tests/unit/test_charm.py
Instead of individually patching each method, mock the entire class. This also ensures we won't "accidentally" use vault.
This PR doesn't reduce code a lot but it does:
1. Reduce the number of places things need to change
2. Make it easier to see what the entire Vault setup looks like from the perspective of the test
3. Make it easier to extract and refactor to reduce code in the future
This could be a first step in a bigger refactor. The next step would be to extract the common vault stuff into a test `setUp` for the tests that is then overridden by the tests that need "non-standard" behaviour.
> chore: Cleanup tests by mocking Vault class

- metadata.yaml
> chore: bump vault to v1.15.6

- pyproject.toml
- requirements.in
- requirements.txt
- test-requirements.in
- test-requirements.txt
- tox.ini
Remove black formatter
As we switched to Ruff, we use it for formatting as well.
- https://github.com/astral-sh/ruff
> chore: remove black formatter

- .github/workflows/dependabot_pr.yaml
Automates dependabot PR review and merge
> feat: Automates dependabot PR review and merge

- lib/charms/vault_k8s/v0/vault_client.py
This will allow us to catch and report errors to the end user, without having to catch `hvac` specific errors.
Specifically, these ones are focused on the functions used to authorize the charm.
> feat: Re-brand Vault errors in some functions where propagating the errors could be useful

- tests/integration/test_integration.py
Marks don't apply to fixtures, so these are not useful.
> test: Remove unnecessary pytest marks

- .github/workflows/promote.yaml
> chore: add promote ci workflow

- lib/charms/vault_k8s/v0/vault_client.py
- lib/charms/vault_k8s/v0/vault_kv.py
- lib/charms/vault_k8s/v0/vault_s3.py
- lib/charms/vault_k8s/v0/vault_tls.py
Should help make logs a little easier to track down
> refactor: Library `logger` improvements

- .github/workflows/cla-check.yaml
Validate that code contributors have signed Canonical's License Agreement.
- https://ubuntu.com/legal/contributors
- https://github.com/canonical/has-signed-canonical-cla?tab=readme-ov-file
> chore: add CLA check

- tests/unit/test_charm.py
- Mock VaultTLSManager and Vault (vault_client) at the class level.
- Fix a test that wasn't testing anything
- Remove extra test setup that was needed because libraries weren't mocked.
> refactor: Test cleanup

- charmcraft.yaml
Some juju secret features and fixes that the charm depends on might not present in lower versions, we make the constraint a bit more specific.
3.1.8 is the current 3.1/stable.
> chore: Make juju constraints more specific in charmcraft.yaml

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
This is an error which occurred infrequently while I was testing Vault auto-unseal on the machine charm.
A best-guess description of what is happening is in the comments, because I think it's a pretty odd scenario.
As discussed in the daily, a follow-up to this might be implementing something from https://discourse.charmhub.io/t/handling-temporary-errors-in-charms/13247 -- but I haven't taken the time to go through it in detail yet. Any patterns for dealing with these types of errors should likely be applied across the charm anyway, and not isolated to this scenario.
> fix: Handle Vault server errors on seal check

- tests/integration/test_integration.py
Improves some ambiguous docstring wording.
> docs: Improve wording

- lib/charms/vault_k8s/v0/vault_tls.py
This is caused by an attempt to update the status of the charm before the storage has been attached. I verified this in the logs, and this is happening moments before the storage is attached through the normal charm lifecycle.
This will set the status to "Waiting for CA certificate to be accessible in the charm", which seems appropriate.
Fixes #407
> fix: Catch ModelError when accessing certs location

- .github/workflows/codeql-analysis.yml
- .github/workflows/main.yaml
To avoid maintaining multiple `main.yaml` and `codeql-analysis.yaml` files for each of the release branches in addition to the main branch we make sure that these workflows run on all of the specified branches
> chore: Run CI for main and release branches too

- tests/integration/test_integration.py
Removed a method that was duplicated
> refactor: Cleanup duplicated method

- lib/charms/vault_k8s/v0/vault_client.py
Lib version was bumped from 18 to 20 in #506 this PR fixes that so the CI can publish the lib.
> fix: Use correct libpatch

- requirements.in
- requirements.txt
- src/charm.py
- test-requirements.in
- test-requirements.txt
- tests/integration/vault_kv_requirer_operator/requirements.in
- tests/integration/vault_kv_requirer_operator/src/charm.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_autounseal.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_kv.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm_authorize_action.py
- tests/unit/test_charm_autounseal_relation_broken.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
- tests/unit/test_charm_create_backup_action.py
- tests/unit/test_charm_install.py
- tests/unit/test_charm_list_backups_action.py
- tests/unit/test_charm_remove.py
- tests/unit/test_charm_restore_backup_action.py
- Use scenario 7 from ops.testing
- Refactor tests
> chore: Refactor tests to use scenario 7

- tests/integration/test_integration.py
This should speed up resolution when waiting on leader election.
> test: Use fast forward in some more integration tests

- lib/charms/vault_k8s/v0/juju_facade.py
- lib/charms/vault_k8s/v0/vault_kv.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_juju_facade.py
- tests/unit/test_charm_authorize_action.py
- tests/unit/test_charm_configure.py
This PR makes some minor improvements to the JujuFacade class and uses it in the charm code:
- Name is not mandatory in the relation functions but either a relation object or the name is required.
- Allow adding description to the secret at creation
- get_bind_address and get_ingress_address
- Use JujuFacade in the charm
- Fix unit tests
> chore: Improves JujuFacade and uses it in the charm code

- src/charm.py
Removes some dead code that is no longer used.
> refactor: Remove some dead code

- .github/pull_request_template.md
I keep forgetting to bump library versions. This might help... sometimes.
> chore: Add version bump checklist item

- src/charm.py
- tests/integration/test_integration.py
Some intermittent issues in the integration test are still present, we improve logs to make debugging those issues when they happen easier.
> chore: Improves logging for easier debugging of integration tests

- lib/charms/vault_k8s/v0/vault_kv.py
Allows the parent class to add attributes to the snapshot so it can be properly restored.
> fix: Ensure parent class attributes are included in snapshot

- lib/charms/vault_k8s/v0/vault_client.py
- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_integration.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_managers.py
- tests/unit/test_charm_configure.py
This implements the PKI manager and moves associated code there.
It also introduces some new tests, and some minor refactoring in the implementation to improve readability (although, I think it could still use some work).
No functional changes (at least, that's the intention).
> feat: Implement PKI Manager

- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- src/templates/kv_mount.hcl
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_managers.py
- tests/unit/test_charm_configure.py
> feat: Implement KV manager

- .github/workflows/main.yaml
Using versioned workflows will allow us to introduce breaking changes without breaking all the builds at once.
> build: Use versioned workflows

- pyproject.toml
- uv.lock
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
> chore: Bumps cosl

- lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
`tls_certificates_interface` is excluded because it appears to be causing "secret removed" errors in the integration tests.
A separate PR will aim to update the `tls_certificates_interface` lib
See also #552
> chore(deps): Update charm libraries, excluding tls_certificates_interface

- tests/integration/helpers.py
- tests/integration/test_integration.py
Add assertion for CA certificate presence and pin self-signed certificates revision
Also, remove an unnecessary wait.
> test: Pin self-signed certificates revision

- CONTRIBUTING.md
Provide instructions on how to run the integration tests locally
> docs: Explain how to run the integration tests locally

- .github/workflows/tics.yaml
- k8s/tox.ini
- machine/tox.ini
Adds a TiCS static analysis workflow to run every week, which is the maximum frequency recommend.
> build: add TICS static analysis workflow

- .github/workflows/k8s-integration-test.yaml
- k8s/tests/integration/test_cos.py
- machine/tests/integration/charm_states/grafana.py
This PR fixes some small issues with the integration tests in CI:
1. Fix the broken metallb range calculation that sometimes selected impossible IPs.
2. Fix the COS deployments to include the right channel.
> fix: Small CI integration test fixes

- docs/reference/index.md
- docs/reference/release_notes.md
> feat: Adds release notes for 1.17

- docs/reference/release_notes.md
The shorter title looks better on read the docs since it is used as the name of the page on the navigation menu
> chore: Change title to Release Notes

- docs/reference/index.md
- docs/reference/supported_releases.md
Here we add the same "supported releases" reference that we have in both the 1.17 and latest version of the docs.
> This change is made against the release-1.16 branch
> docs: add supported releases reference (in 1.16 release)

- .github/workflows/main.yaml
- .github/workflows/trivy.yaml
Set permissions explicitly when calling shared workflows
> chore: Set permissions explicitly when calling shared workflows
