canonical/vault-k8s-operator

- lib/charms/tls_certificates_interface/v1/tls_certificates.py
With tls_certificate_interface 1.6 it is not possible to relate vault to multiple applications. Vault unit goes to error state with the message
ops.model.TooManyRelatedAppsError: Too many remote applications on certificates (2 > 1)
Updating tls_certificate_interface to 1.10 allows to relate to multiple applications.
Please include a summary of the change. Please also include relevant motivation and context. List any dependencies that are required for this change.
> bump tls_certificate_interface lib to 1.10

- .github/workflows/main.yml
- charmcraft.yaml
- tests/integration/test_integration.py
The goal of the PR is to fix the following:
- The Cryptography library is complaining about missing `GLIBC_2.33` which seems not to be present on ubuntu20.04, this causes the charm to be in error statue.
When using Ubuntu 22.04 to build the charm, the charm deploys correctly.
> Uses Ubuntu 22.04 to build and test the charm

- lib/charms/observability_libs/v1/kubernetes_service_patch.py
Fix #22
Upgrading kubernetes_service_path to 1.7 allows the charm to ensure its service definition stays correct
> Upgrade kubernetes_service_patch library

- README.md
- charmcraft.yaml
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/vault.py
- tests/unit/test_charm.py
Here we enable TLS in the Vault cluster:
- On install, a private key, CA certificate and certificate are generated, stored in juju secret and pushed to the workload
- Those certificates are refered to by the nodes in their pebble configuration
- Modifications to README.md to display TLS related changes
_Note: Currently, we explicitely do not verify the CA in the vault API calls (`verify=False`). In a future PR we would probably want to enable this and reference to Vault's CA certificate. This PR is big and complex enough as is to include this change here._
> [feat] Enables TLS in Vault cluster

- src/charm.py
- tests/unit/test_charm.py
Fix #37 
Services reaching Vault from inside K8S (no external addressing) use the loadbalancer primitives offered by K8S.
Adding to Subject Alt Names:
- Service name as DNS SAN
- Ingress address (ClusterIP) as IP SAN
I'm not sure that's the right way to handle, since current TLS handling does not handle scaling, TLS management will most likely evolve. Happy to discard if that's not wished.
> [Fix] Add subject and ingress address to subject alt names

- .github/workflows/publish-charm.yaml
Publishes vault_kv library when we publish the charm.
> Fix: Publish library when publishing charm

- src/charm.py
- tests/unit/config_with_raft_peers.hcl
- tests/unit/config_with_raft_peers_equivalent.hcl
- tests/unit/test_charm.py
Fixes retry join comparison in config file. The retryjoin stanza is typically a list. When comparing the file content, we should not care about ordering, therefore we are now converting to set before making the comparison.
> [bugfix] Fixes retry join comparison in config file

- README.md
- src/charm.py
- tests/unit/test_charm.py
Units used to share the same certificate which was causing an issue where SSL clients like the vault client would throw errors because the Vault instance IP did not match its certificate IP for non-leader units (since it was the leader that generated the cert). This PR makes it so that each unit generates its own certificate on charm install. They are all signed by the same CA certificate which is generated once by the leader.
Fixes #50
> [bugfix] Implements per-unit TLS certificate

- tests/unit/test_charm.py
This PR builds on what @benhoyt proposed in PR #55 and reduces the amount of mocking in unit tests. We remove need for mocking push, pull and exists alltogether.
> [chore] Reduces amount of mocking by leveraging ops features

- metadata.yaml
Adds discourse Charmhub docs pointing to:
- https://discourse.charmhub.io/t/vault-operator-kubernetes/12123
> chore: Adds discourse Charmhub docs

- lib/charms/vault_k8s/v0/vault_kv.py
- src/charm.py
- src/vault.py
- tests/unit/test_charm.py
- tests/unit/test_vault.py
Enables audit device upon initialisation of Vault
Adds unit tests.
Fixes tests.
Fixes tox issues.
Bumps lib patch to publish change from [this merged pr](https://github.com/canonical/vault-k8s-operator/commit/c5a7608a3619f739ac6449aea39e60a40c32ca3a#diff-e441c2125fb9fd9548dec33cc23c5d2cf968aa96e7b516a2c5f1045148470593R123).
> feat: Enables audit device upon init

- src/charm.py
- src/vault.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
- tests/unit/test_vault.py
Simplifies event management by using a central `_configure` event handler. Using this handler makes it so that on any state-affecting event (config changed, peer relation changed), we look at the state of the world (relations, configs) and the state of the charm and make the appropriate changes. Through the use of the central event handler, this change gets rid of most `defer()` in the code as well as the need for "wait_for_xyz" methods .
1. This PR contains no behaviour change (i.e. integration tests are identical). It's really about "how" events are handled rather than "what" the charm does.
2. Follow up PR's will get rid of defers in the KV handler. We are not doing this here because this PR was large enough as is.
> feat: Simplifies event management

- tests/integration/test_integration.py
- tests/integration/vault_kv_requirer_operator/actions.yaml
- tests/integration/vault_kv_requirer_operator/charmcraft.yaml
- tests/integration/vault_kv_requirer_operator/metadata.yaml
- tests/integration/vault_kv_requirer_operator/requirements.txt
- tests/integration/vault_kv_requirer_operator/src/charm.py
- tests/integration/vault_kv_requirer_operator/src/vault_client.py
This PR introduces a Vault KV requirer charm used in the integration tests to validate the `vault_kv` integration. The requirer charm uses the `vault_kv` library to ask Vault for a new secret mount and creates/get secrets on this mount using Juju actions.
It is currently hard to validate that code changes do not impact the vault_kv integration as requirers are in other projects (ex. Openstack). With these new tests here we can increase confidence that vault code changes do not impact the integration.
> feat: Adds integration tests for Vault KV integration

- src/charm.py
- tests/unit/config.hcl
- tests/unit/test_charm.py
Fixes #69 by using the FQDN to connect to the vault instance instead of using the IP address.
Using the IP address caused an issue because the IP address would change after a crash or removal of a pod. In turn, this would cause the TLS certificate to no longer be valid, as the TLS certificate is validated against the new IP address (but was only issued for the old IP address). We could re-issue the certificate, but the certificate is also valid for anything which uses the same FQDN which the new pod will share.
This change removes the IP address from the certificate, and relies on the FQDN instead.
> fix: Use fqdn instead of IP address to connect to vault

- tests/integration/test_integration.py
Using `self` isn't necessary here
> chore: Don't use `self` where it's not necessary

- src/charm.py
- tests/unit/config.hcl
By using hostnames instead of IP addresses in Vault's `cluster_address`, we make it possible for Vault units to crash and come back up with different IP's. Now we should be able to confidently delete any pod in the cluster and have Vault stay alive.
Before this PR:
```
guillaume@potiron:~$ vault operator raft list-peers
Node               Address             State       Voter
----               -------             -----       -----
dev-vault-k8s/0    10.1.182.18:8201    leader      true
dev-vault-k8s/1    10.1.182.57:8201    follower    true
dev-vault-k8s/2    10.1.182.45:8201    follower    true
```
After this PR:
```
guillaume@potiron:~$ vault operator raft list-peers
Node               Address                                                       State       Voter
---- …
```
> fix: Raft clustering uses hostnames instead of IP addresses

- requirements.txt
- tests/unit/test_charm.py
Bumps to ops 2.9.0. This required some changes in our tests. More specifically, "in 2.9 Harness does the same permission check as Juju whereas previously it would allow a non-leader unit to manage app secrets (this fails if you do it in prod)." (taken from a conversation with @tonyandrewmeyer ).
> chore: Bumps to ops 2.9.0

- README.md
- metadata.yaml
Bumps the Vault rock version to 1.15.3.
> chore: Bumps Vault version to 1.15.3

- test-requirements.txt
Our unit tests and integration tests were failing because of an update in `macaroonbakery`, used by the `juju` package. 
```
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
1. Downgrade the protobuf package to 3.20.x or lower.
2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
> fix: Freezes macaroonbakery==1.3.2 to avoid protobuf error

- README.md
- metadata.yaml
Now that Vault 1.15.4 is available and published, here we update the k8s operator to use it.
> chore: Bumps vault OCI version to 1.15.4

- actions.yaml
- src/charm.py
- tests/unit/test_charm.py
Adds actions to set unseal keys and root token, these actions can be useful to recover the charm if the unseal key of vault changes while the one stored in the juju secret doesn't get updated or gets updated incorrectly.
Adds unit tests
> feat: Adds actions to set unseal keys and root token

- src/charm.py
- tests/unit/test_charm.py
This PR adds some unit tests for the `on_new_vault_kv_client_attached` function and refactor that function. The design of the function and the functionality are unchanged for now, the aim is to improve testing for further refactoring.
> chore: minor refactoring of `on_new_vault_kv_client_attached` and adds some unit tests.

- lib/charms/vault_k8s/v0/vault_client.py
According to https://github.com/canonical/charmcraft/issues/214, charm library renaming is not yet supported. 
So, this renames the library by providing a new `LIBID`. that was created with the correct name.
> chore: Rename vault lib to vault_client

- requirements.in
The ingress lib (`ingress.py`) requires `pydantic` to be <2.
This PR pins the version.
> fix: Pins version of pydantic as required by ingress.py

- tests/integration/test_integration.py
Use `in` operator so that logic is applied correctly. Previous code would always return true.
> test: Fix for integration test

- .github/workflows/main.yaml
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm.py
- Uses concurrency in GH actions
-  Avoids having the CI running more than once at a time for the same dev branch
- Main branch is ignore by always assigning the run id to the actually running ci so it isn't cancelled
- Fixes docstring inconsistencies
> feat: Uses concurrency in GH actions

- config.yaml
- lib/charms/tls_certificates_interface/v3/tls_certificates.py
- lib/charms/vault_k8s/v0/vault_client.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- tests/integration/test_integration.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
- tests/unit/lib/charms/vault_k8s/v0/tls.py
- tests/unit/test_charm.py
Vault can now act as an intermediate CA where the parent CA is the provider side of the newly added  `tls-certificates-pki` integration. Here we add the requirer side of the `pki` integration .
Upon certificates-pki-request relation joined:
- Configure the PKI mount, configures the PKI intermediate CA (generates a CSR)
- Send that CSR over to the relation provider.
- Store the CSR in a Juju secret
Upon Certificate Available:
- Validate that the received cert matches the stored CSR
- Set the PKI intermediate CA certificate
- Set the PKI charm role
- A follow up PR will implement the provider side where requires will be able to integrate with Vault using the `tls-certificates` integration that we will alias to `vault-pki`.
- This PR depends on this PR being merged first: …
> feat: add requirer side of pki integration

- lib/charms/vault_k8s/v0/vault_tls.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm.py
Centralize status management using the Collect Status event handler from ops. 
As we are adding more event handlers in the context of PKI, it became clear that having central status management would simplify operations. Specifically, without this change here, we would have had to move the charm to blocked status in the `RelationJoined` event in cases where the `common_name` config is not set. That would have been an issue as a follow-up `update_status` event would have overwritten this status.
> chore: centralize status management

- pyproject.toml
For whatever reason, dependabot appears to expect the `pyproject.toml` to be in this format. This should get dependabot working again.
I tested this on my fork.
This same change will be applied to https://github.com/canonical/vault-operator/ upon successful dependabot run.
> chore: Change formatting of pyproject.toml

- requirements.in
- requirements.txt
Bump pydantic to v2.5.3.
Unfortunately we can't go higher at the moment because the `rustc` package from the apt repo for Ubuntu 22.04 used in the Charm isn't compatible. You can read more about this here: https://github.com/pydantic/pydantic-core/issues/1176
> chore: bump pydantic to v2.5.3

- tests/integration/test_integration.py
The `vault-k8s` integration tests are flaky and one of the reason is that we are using Traefik from its edge branch. Specifically, we have failing CI's which prevent unrelated changes from being merged. Here we move to use stable instead to hopefully gain some stability. 
- Failing CI: https://github.com/canonical/vault-k8s-operator/actions/runs/8145030648/job/22260393500?pr=213
> fix: install traefik from stable channel

- lib/charms/vault_k8s/v0/vault_client.py
These are necessary methods to implement manual unseal.
I know that @Kayra1 is working on a bit of a refactor in this class, so I tried to keep this as minimal as possible for now.
See https://github.com/canonical/vault-operator/pull/62 for the downstream dependency / usage.
> feat: Add approle login, and charm policy creation to the Vault client

- lib/charms/vault_k8s/v0/vault_tls.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
Before this change, the function just checked for the existence of the storage, but didn't check if the file was actually there.
We now ensure that the file actually exists.
> fix: Detect if tls file actually exists

- lib/charms/vault_k8s/v0/vault_tls.py
Bumps the version of the `vault_tls` library. Should have been bumped in #246 .
> chore: Bump vault_tls version

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
Make the CIDRs list optional in the vault client calls.
Context: https://github.com/canonical/vault-operator/pull/62#discussion_r1516346734
> feat: Make CIDRs list optional

- lib/charms/vault_k8s/v0/vault_kv.py
- requirements.txt
- src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_vault_kv.py
- tox.ini
Here we update the `vault_kv` library to make it possible for the charm to get kv requests at any moments using `getters`. The charm uses those getters to sync kv requests on update status events, just like we do for tls certificate requests.
1. Move all relation data logic to the kv library. You won't see any `relation.data.get()` in charm code anymore. It all lives in the `vault_kv` lib, where it belongs.
2. Standardise resource provider approach between tls certificates and kv secrets, both offer pull based mathods allowing to get the outstanding requests at any moment.
3. Get rid of `event.defer()` for kv requests. 
4. This is a major change for the provider side of the lib for which only vault-k8s uses. The intent was to make this change before using it in the machine version of the …
> chore: use update status event to sync kv requests

- .github/workflows/build.yaml
- .github/workflows/integration-test.yaml
- .github/workflows/main.yaml
- .github/workflows/publish-charm.yaml
- tests/integration/conftest.py
- tests/integration/test_integration.py
We move the charm build process to its own workflow stage. We build the charm, we test it, and we publish it, all with the same artifact. This brings the k8s charm in line with the machine charm approach. 
```
tox -e integration -- \
--charm_path=<vault charm path> \
--kv_requirer_charm_path=<KV requirer charm path>
```
1. This reduces the amount of resources taken by the integration tests which is the step that takes the largest amount of GH runners resources.
2. Each step has its own precise role instead of having the built artifact be a side effect of running the integration tests. In other words, we won't be noticed of a build failure through an integration test failure anymore. 
- In cases where the CI fails because the charm doesn't build, it's quicker to identify that this isse is …
> chore: build charm in independent workflow step

- lib/charms/vault_k8s/v0/vault_kv.py
- src/charm.py
We now check if the relation is active before syncing kv values in all relations. Broken relations still count as relations in the relation-broken event and we must make sure that we don't insert data in there.
Fixes #241
> fix: check if relation is active before syncing kv

- lib/charms/vault_k8s/v0/vault_client.py
From #303: 
"looks like this crash is happening in collect-status right after the tls integration is gone. My initial impression is that when tls-certificates-access-relation-changed fires, the workload is restarted, and collect status immediately tries to connect to a workload that's restarting. This doesn't explain how it may sometimes work. Maybe it's happening so close to the pebble call that an http request gets through before k8s/pebble could schedule a restart.
Connection Refused is being caught at the client level right now, but it seems like python is actually throwing a requests.exceptions.ConnectionError to the client code. This is the exception that should probably be caught in Vault.authenticate."
Fixes #303
> fix: Catch connection errors when logging in to vault

- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm.py
Fixes #311. Checks if the CA file exists in Vault instead of just checking if the storage path is available for collect status.
> fix: Check for CA file availability instead of storage itself

- lib/charms/vault_k8s/v0/vault_tls.py
- src/charm.py
- tests/integration/vault_kv_requirer_operator/src/charm.py
We refresh the juju secret when checking its content making sure we are reading its latest value instead of an older one.
> fix: use latest version of juju secret

- tests/unit/test_charm.py
Ops recently added support for running actions using the `run_action` method. This allows for triggering action events without directly making calls to the event handlers. In practice this also means we can refactor the handlers names without breaking tests. This is only a change in unit tests.
> chore: use ops.testing.run_action instead of directly calling event handlers

- requirements.in
- requirements.txt
- test-requirements.in
- test-requirements.txt
Moves boto3 related dependencies to requirements.in
boto3-stubs is a transitive dependency of types-boto3 that is used in the test-requirements, therefore to avoid any conflicts we keep all boto3 related dependencies in one place.
> fix: Moves boto3 related dependencies to requirements.in

- src/charm.py
- tests/unit/test_charm.py
Before we just retrieved the service object, so the function would always return true if the service existed.
This was masked by the way we delegate methods to the underlying `OpsContainer`, which is probably worth refactoring, but not necessary for this fix.
> fix: check for running Vault service correctly

- src/charm.py
- tests/unit/test_charm.py
Currently there is no output for the `authorise-charm` action when it is successful.
I think it is better to have a clear feedback when the action succeeds especially because some Juju versions fail to show failure messages.
> chore: Adds action result for authorise charm action

- lib/charms/vault_k8s/v0/vault_kv.py
When the Vault KV library updates the login credentials the requirer must use the refresh parameter when fetching the credentials secret to get the updated ones.
> fix: Improves docstring to instruct the requirer to refresh the credentials secret when fetching it.

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
- tests/integration/test_integration.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
- tests/unit/test_charm.py
Since v1.11 Vault now creates a new issuer whenever a CA is added in PKI. However the default issuer is not updated by default, so when the charm checks the current intermediate CA it will get the one of the default (first) issuer, causing the charm to generate a new CSR and a new CA and push that to Vault over and over again once the common name is changed.
Although the charm would work as expected and provide certificates under the new common name, if the charm is deployed for long enough one would see a large number of CAs created.
This PR fixes that issue, now when a new common name is set and new CA is created we make sure that the new issuer is the default. This is achieved by setting the default issuer to the latest issuer after the creation of the first issuer.
**Note for …
> fix: Sets the latest issuer to be the default issuer in PKI

- lib/charms/vault_k8s/v0/vault_client.py
- tests/integration/test_integration.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
- We validate that the issuers config is not yet updated before updating it again. This should prevent us from writing to that config more than once avoiding any unexpected behaviour.
- The integration test changes introduced in #386 made the CI unstable. The changes in the issuers config might not be immediately visible in vault, for that in this PR we wait until all units are active idle (that indicates that the Vault API is available again).
> fix: Validate if issuers config was already updated before updating it

- lib/charms/vault_k8s/v0/vault_autounseal.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_autounseal.py
- tests/unit/test_charm.py
There's no need to infer this, and adding it makes the interface more flexible.
> feat: Include the mount_path in the autounseal databag

- .github/workflows/integration-test.yaml
We use selfhosted runners to have more space to do our integration tests
> chore: add self hosted runners to integration tests

- charmcraft.yaml
- src/charm.py
- tests/integration/test_integration.py
- tests/unit/test_charm.py
This change includes moving from using an action to authorize the charm to granting a user secret to authorizing a charm. The process is simply:
```shell
juju add-secret approle_authorization_token token=$VAULT_TOKEN
juju grant-secret approle_authorization_token vault-k8s
juju run vault/leader authorize-charm secret-id=$secret-id
```
The documentation will need to be updated.
> feat: Use juju secrets instead for authorize-charm

- tests/integration/helpers.py
- tests/integration/test_integration.py
After publishing a new version of the tls requirer, the integration tests will fail. This change attempts to resolve those issues.
`get_unit_status_messages` and `wait_for_status_message` are largely taken from similar versions in the main `test_integration.py` file that were written specifically for Vault. A future PR will consolidate these and remove the Vault-specific versions.
> test: Fix integration tests for latest tls requirer

- lib/charms/vault_k8s/v0/vault_client.py
This isn't an error. It is actually expected in normal operation of the charm, and the error logs are misleading.
> refactor: Downgrade log to warning level

- tests/integration/conftest.py
- tests/integration/test_integration.py
Allow passing the PKI requirer as an optional parameter when running the integration tests.
This was useful when debugging and preparing fixes in tls-requirer-operator. Presumably, it will be useful again in the future.
> test: PKI requirer as optional test parameter

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
This PR introduces a change that [configures the raft backend](https://developer.hashicorp.com/vault/api-docs/system/storage/raftautopilot#set-configuration) when the charm is being authorized. These configuration options do not have a relevant field in the vault.hcl config file, so they have to be executed (relatively) manually.
Vault only allows a minimum of 3 for the minimum quorum for automatic dead server pruning. This means that dead server 2 and 3 will never be cleaned. On top of that, we already do our best to update the vault config file and remove the peers that are not planned to be there, so this is really a plan C thing.
> feat: enable dead server pruning

- lib/charms/vault_k8s/v0/vault_tls.py
The logs for Vault charms contain many instances of the `Sent CA certificate to other relations`, even when this relation does not exist. We should only log when the actual action was completed.
```
unit-vault-2: 13:23:53 INFO unit.vault/2.juju-log [vault_tls] Sent CA certificate to other relations
unit-vault-2: 13:23:54 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-vault-0: 13:23:59 INFO unit.vault/0.juju-log [vault_tls] Sent CA certificate to other relations
unit-vault-1: 13:23:59 INFO unit.vault/1.juju-log [vault_tls] Sent CA certificate to other relations
unit-vault-0: 13:23:59 INFO juju.worker.uniter.operation ran "update-status" hook (via hook dispatching script: dispatch)
unit-vault-1: 13:23:59 INFO …
```
> chore: only log when action is completed

- src/charm.py
- tests/unit/test_charm.py
Part of the solution for: #415 
Currently, we store the CSR in a secret so that we can compare the certificate that is returned with the one we sent. However, we already store this CSR in the relation databag, and we are only ever requesting a single certificate.
Removing the dependence on secrets will simplify the solution for #415 because we won’t need to consider as many cases in the event that adding or updating the secret fails. Furthermore, it simplifies our code.
> refactor: Remove secret usage from Vault PKI implementation for CA CSR

- lib/charms/vault_k8s/v0/vault_kv.py
The source of issue #437 was because the code example in our vault kv docs had a bug in it. This PR fixes that doc.
Closes #437
> fix: vault KV python example docs

- src/charm.py
- tests/integration/test_integration.py
For the holistic pattern to work, intermittent issues retrieving secrets or writing secrets need to be ignored. These present themselves as generic `ModelError`s on the ops framework side. 
Side note: Anything that stores a secret also needs to be written such that it could fail, and correct itself on the next event (reentrant). The existing implementations already behaved this way, with the exception of the PKI implementation which was refactored in #434 
Fixes #415
> fix: Handle secret retrieval/storage errors

- lib/charms/vault_k8s/v0/vault_kv.py
- src/charm.py
- tests/integration/vault_kv_requirer_operator/src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_kv.py
- tests/unit/test_charm.py
**Note**: This is a breaking change on the provider side, but since this is handled in the same PR in Vault I think it should be okay. No breaking changes on the requirer side by allowing it to set the egress subnet as string or as list.
Instead of using the `interfaces` of the network binding to configure the approle in vault we use the list of `egress_subnets`.
Juju describes the interfaces as:
```
A list of network interface details. This includes the information
about how the application should be configured (for example, what IP
addresses should be bound to).
```
While it describes the `egress_subnets` to be:
```
A list of networks representing the subnets that other units will see
the charm connecting from. Due to things like NAT it isn't always possible to
narrow it down to a …
```
> fix: Uses egress subnet list to configure approle

- lib/charms/vault_k8s/v0/vault_kv.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_kv.py
- tests/unit/test_charm.py
This PR introduces some changes and refactors the code to ensure:
- Vault KV secrets of a specific unit are removed when the unit relation departs
- Secret ID is used to get the secret as a workaround to the issues reported [here](https://bugs.launchpad.net/juju/+bug/2075153) and [here](https://github.com/canonical/operator/issues/1312).
- Adds the `VaultKvClientDetachedEvent` custom event that wraps the relation departed event.
- Adds unit tests.
> fix: Removes the vault-kv secret when the unit is removed

- tests/unit/lib/charms/vault_k8s/v0/test_vault_kv.py
Replace harness with scenario for unit testing. The change was already done for the `vault TLS` library. Here we do it for `vault-kv` and follow-up PR's will take care of it for the remaining test files. 
The scenario framework enforces our current approach with:
- Arrange (state in)
- Act (juju event)
- Assert (state out)
This makes tests easier to read, to write, and to parameterise .
- https://github.com/canonical/ops-scenario
> refactor: replace harness with scenario for unit testing (vault-kv)

- lib/charms/vault_k8s/v0/vault_autounseal.py
- lib/charms/vault_k8s/v0/vault_client.py
- lib/charms/vault_k8s/v0/vault_kv.py
- lib/charms/vault_k8s/v0/vault_s3.py
- lib/charms/vault_k8s/v0/vault_tls.py
- src/charm.py
- tests/integration/vault_kv_requirer_operator/src/charm.py
- `Optional` was a poor choice of words. It doesn't fit well in all contexts and it conflicts with the already established meaning of an optional argument (you can have an optional argument that isn't optional).
- `Optional` also makes a lot less sense from an English perspective when it's a return value.
- It's easier to read (subjective)
- It's the new way, and new things are _always_ better,
- Also removes use of `Union`
> refactor: Replace optional with newer syntax

- lib/charms/vault_k8s/v0/vault_autounseal.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_autounseal.py
Replace unit tests from harness to scenario for the Vault autounseal integration.
Doing so I identified the problem causing infinite credentials Juju secrets being created. The Vault autounseal provider charm would look at the remote application's databag for the `credentials_secret_id` field and if the field wasn't there it would create a Juju secret. This condition was always true since the `credentials_secret_id` is in the local application databag, not the remote one. 
Fixes #457 
The scenario framework enforces our current approach with:
- Arrange (state in)
- Act (juju event)
- Assert (state out)
This makes tests easier to read, to write, and to parameterise .
- https://github.com/canonical/ops-scenario
> fix: read local app data and use scenario for unit tests (vault autounseal)

- tests/integration/test_integration.py
There was a breaking change in the tls-certificates-requirer charm, here we specify the revision not to depend on changes in that charm.
> fix: Specify tls requirer revision

- grafana.lint
I wasn't able to figure out why these lint rules were failing. I tried a few different things but my grafana knowledge is limited.
For now, we ignore the rules to get the build running again.
> build: Ignore the new grafana logql linter rules

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
Also, remove the type ignore.
If this were bytes, it implies that the streamingbody would be converted to bytes before restoring, and would load the whole thing into memory.
> style: Loosen `restore_snapshot()` typing

- lib/charms/tls_certificates_interface/v4/tls_certificates.py
- lib/charms/vault_k8s/v0/vault_client.py
- lib/charms/vault_k8s/v0/vault_tls.py
- src/charm.py
- tests/unit/certificates.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_tls.py
- tests/unit/test_charm_collect_status.py
- tests/unit/test_charm_configure.py
Fixes #500 
- Checks if there is a CA that can issue certificates (Vault does not allow issuing certificates that would outlast the CA)
- Sets the ttl of the pki role to half of the validity of the CA, this will be used by Vault to set validity of issued certificates
- Adds a unit test
**Note to reviewer**: 
- It might help to read spec TE118 while reviewing this.
> fix: Makes sure there always is an active issuer in Vault PKI

- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
Currently, we have a mashup of unittest and pytest.
Although the class inherits from unittest, we're using pytest to run the tests. This works fine in the basic cases, but doesn't work when you try to use any of the features of either framework. For example, neither pytest parameterize or unitttest subtests work.
> refactor: Removes unittest, so pytest operates as expected

- lib/charms/vault_k8s/v0/vault_client.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_client.py
Removing Vault units while raft is in unhealthy state causes the charm to go into an unrecoverable error state. Handling these errors allows the charm to be removed gracefully.
TODO:
> fix: handle raft errors when unhealthy

- lib/charms/vault_k8s/v0/vault_client.py
- src/charm.py
- tests/unit/test_charm_authorize_action.py
When deploying Vault with multiple units and pods restart, they do not come back online. Vault seems to be pruning them because they have been offline for too long and do not accept them to come back. 
Here we get rid of this automatic dead server pruning and only remove nodes from the cluster on remove event. 
Fixes #523
> fix: remove dead server pruning

- .gitignore
Ignores the (generated) charm tracing buffer file
> chore: Ignore charm tracing buffer

- lib/charms/vault_k8s/v0/juju_facade.py
- lib/charms/vault_k8s/v0/vault_tls.py
- tests/unit/lib/charms/vault_k8s/v0/test_juju_facade.py
Implements the `JujuFacade` class and uses it in `VaultTLSManager`
This PR implements TE109.
It regroups exceptions and raises them wrapped in exceptions defined in the library.
For example `get_secret` would still raise an exception if the secret was not found, wrapped in `NoSuchSecretError` however the advantage of juju_facade is that the caller doesn't need to run `get_secret`, then `secret.get_content` and finally `set_content` to change the secret content. It is all wrapped into one call. For more info please read the spec.
> feat: Implement the JujuFacade wrapper class

- lib/charms/vault_k8s/v0/vault_autounseal.py
The type hints already specify the type should be `ops.Relation`, so this shouldn't be necessary.
> refactor: Remove unnecessary check

- .github/workflows/build.yaml
- .github/workflows/integration-test.yaml
Uses 5.0/stable for lxd instead of 5.x/stable to avoid build failures on version bumps.
> build: Use 5.0 stable for lxd to avoid build failures on version bumps

- .github/workflows/integration-test.yaml
- Bump Juju to `3.6/stable`
- Bump MicroK8s to `1.31-strict/stable`
> chore: bump juju and microk8s versions in CI

- lib/charms/vault_k8s/v0/vault_autounseal.py
- src/charm.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_autounseal.py
- tests/unit/test_charm_configure.py
Addressing https://github.com/canonical/vault-operator/pull/333#discussion_r1867994211
Renames `get_outstanding_requests` (and associated code) to `get_relations_without_credentials`. This code is for detecting which auto-unseal relations still need credentials generated for them, so the new name should be easier to follow.
> refactor: Rename requests --> relations

- .gitignore
There is a new library that must be copied for the integration tests, so the gitignore is modified to capture anything in the directory.
This ensures the file isn't accidentally committed after running the integration tests locally.
> chore: Ignore all libs that must be copied for the integration tests to run

- lib/charms/vault_k8s/v0/vault_managers.py
- src/container.py
This ensures that pebble is accessible before running the hook, otherwise we could get a pebble error when trying to do something like access the certificate in the workload.
This issue is currently causing plenty of integration test failures. This change appears to fix that.
> fix: Check if the workload is accessible before running hook

- lib/charms/vault_k8s/v0/juju_facade.py
- tests/integration/test_integration.py
This PR includes a fix to retry the authorize_charm action in the integration test if it fails, some intermittent issue causing the charm to fail happened because Vault could not authenticate using the Token provided in the action which can happen for things like `VaultError` and `ConnectionError`.
The PR also removes the logs from `juju_facade` where an exception is raised.
> fix: Improves JujuFacade and the integration tests

- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_managers.py
Since these all come from a module named vault_managers, it is  redundant to prefix these.
> refactor: Remove "Vault" from the beginning of Vault Managers.

- tests/integration/test_integration.py
I believe this was the original intention of #567 
This change retries the action itself. The current code just retries retrieving the action output, but only runs the action once.
> fix: retry authorize-charm

- tox.ini
Use uv sync in tox to use locked versions. This ensures that tox will not install newer packages when running.
> fix: Use uv sync in tox to use locked versions

- lib/charms/vault_k8s/v0/vault_client.py
Bumps the vault client version for changes that have already been made.
I forgot this in #559
> fix: Bump vault client version

- lib/charms/vault_k8s/v0/vault_client.py
- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- tests/unit/fixtures.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_managers.py
- tests/unit/test_charm_create_backup_action.py
- tests/unit/test_charm_list_backups_action.py
- tests/unit/test_charm_restore_backup_action.py
> feat: Implements the backup manager

- tests/unit/fixtures.py
- tests/unit/test_charm_configure.py
Patchers made more sense when we were using unittest, and we had setup and teardown methods. Now that we've moved to pytest, we can use contextmanagers by yielding within the fixture.
This ensures that the patches are properly undone after each test.
> refactor: Use contextmanagers instead of patchers

- .github/workflows/integration-test.yaml
- .gitignore
- pyproject.toml
- uv.lock
Sets up Allure Reports at https://canonical.github.io/vault-k8s-operator/
> feat: allure reports in CI

- src/charm.py
- tests/unit/test_charm_authorize_action.py
- tests/unit/test_charm_collect_status.py
We were creating an approle that would expect its user to be in a /24 subnet defined by the leader's bind address.  However, there is no guarantee that different charm units will have bind addresses in the same /24 subnet.  This behavior caused a bug in non /24 subnet, and would also cause issues if/when units are in different subnets alltogether.  Here we are simply removing any IP requirement from the approle. 
Fixes #582
> fix: remove CIDR from approle

- charmcraft.yaml
- lib/charms/vault_k8s/v0/juju_facade.py
- lib/charms/vault_k8s/v0/vault_managers.py
- src/charm.py
- tests/unit/lib/charms/vault_k8s/v0/test_vault_managers.py
Implements bootstrapping raft via an action as per TE133.
The user experience is as follows:
```
juju scale-application 1
juju run vault/leader bootstrap-raft
juju scale-application 5
```
Cleanup of the `peers.json` file is done automatically by Vault once the single-unit cluster recovers.
CharmHub docs to follow in a separate task.
> feat: Allow bootstrapping raft via an action

- lib/charms/vault_k8s/v0/vault_helpers.py
This change was introduced in the machine charm to handle the case when retry joins are not present in the config. We include this check in the lib.
> fix: Handle when retry-joins don't exist in the config

- lib/charms/vault_k8s/v0/vault_helpers.py
- lib/charms/vault_k8s/v0/vault_managers.py
- pyproject.toml
- src/charm.py
- src/templates/vault.hcl.j2
- tests/unit/test_charm_configure.py
This change provides the vault token via an environment variable, [as recommended by the docs](https://developer.hashicorp.com/vault/docs/configuration/seal/transit#authentication). This avoids writing the token to disk, which has security implications.
> feat: Provide the Vault token via an env var

- charmcraft.yaml
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- src/charm.py
Implements the requirer side of ingressPerUnit
When Vault is only accessible behind an ingress the user needs to access each unit individually to unseal for example.
> feat: Implements the requirer side of ingressPerUnit

- .github/workflows/main.yaml
- machine/CONTRIBUTING.md
Charm publishing is now broken on `main`.  The upload-charm github action uses the `charmcraft.yaml` file to figure out the resource to be uploaded. Here we point to the right charm directory to allow the workflow to function.
To do before merging:
- https://github.com/canonical/identity-credentials-workflows/pull/18
> fix: point to charm directory

- .github/workflows/promote.yaml
Unless a `charm-path` is provided, the `release` action assumes the charm path is the current working directory. Since we are working in a repo with multiple charms, we must now provide the charm path and let users select which charm to promote via a new `charm` action input parameters.
> fix: charm selection in promote action

- .github/workflows/tics.yaml
Currently, this workflow will instantly fail because the upstream one doesn't exist yet, however, including this workflow file in the main branch will allow me to test the workflow and upstream workflow using `workflow_dispatch` on a development branch.
I'd like to be able to run here so I can try working in a repo with multiple charms.
> build: add TICS static analysis workflow

- k8s/terraform/README.md
- k8s/terraform/main.tf
- k8s/terraform/outputs.tf
- k8s/terraform/variables.tf
- k8s/terraform/versions.tf
- machine/terraform/README.md
- machine/terraform/main.tf
- machine/terraform/outputs.tf
- machine/terraform/variables.tf
- machine/terraform/versions.tf
Add Terraform modules for operating Vault in both Kubernetes and Machine models.
- A Kubernetes cluster
- A Juju controller bootstrapped onto the Kubernetes cluster
- The Juju client
- Terraform
On the host machine create a new directory called terraform:
```shell
mkdir terraform
```
Inside newly created terraform directory create a versions.tf file:
```shell
cd terraform
cat << EOF > versions.tf
terraform {
required_providers {
juju = {
source  = "juju/juju"
version = ">= 0.12.0"
}
}
}
EOF
```
Create a Terraform module containing Vault K8s:
```shell
cat << EOF > main.tf
resource "juju_model" "demo" {
name = "demo"
}
module "vault-k8s" {
source = "git::https://github.com/canonical/vault-k8s-operator//k8s/terraform?ref=dev-tf"
model      = juju_model.demo.name
}
EOF
```
Initialize Juju …
> feat: add terraform modules for operating Vault

- k8s/charmcraft.yaml
- k8s/lib/vault/vault_client.py
- k8s/lib/vault/vault_managers.py
- k8s/src/charm.py
- k8s/tests/integration/test_integration.py
- k8s/tests/unit/fixtures.py
- k8s/tests/unit/lib/test_vault_managers.py
- k8s/tests/unit/test_charm_collect_status.py
- k8s/tests/unit/test_charm_configure.py
- machine/charmcraft.yaml
- machine/lib/vault/vault_client.py
- machine/lib/vault/vault_managers.py
- machine/src/charm.py
- machine/tests/integration/test_integration.py
- machine/tests/unit/fixtures.py
- machine/tests/unit/test_charm_collect_status.py
- machine/tests/unit/test_charm_configure.py
- Feature manager for ACME is added
- A new TLS integration is added to get the intermediate CA for ACME
- ACME is enabled when the integration is created
- Added unit and integration tests
- Change done in both k8s and machine
To test:
- Deploy vault and self-signed-certificates
- Do the necessary steps to get vault to the active status (init and unseal)
- Integrate with the tls provider through the `tls-certificates-acme` integration
Now ACME should be enabled, use your favorite client to test (for example lego cli)
> feat: Enable ACME in Vault charms

- k8s/charmcraft.yaml
- k8s/lib/vault/vault_managers.py
- k8s/pyproject.toml
- k8s/src/charm.py
- k8s/tests/unit/config.hcl
- k8s/tests/unit/lib/test_vault_tls.py
- k8s/tests/unit/test_charm_restore_backup_action.py
- k8s/uv.lock
Use peer relation to share peers addresses. This fixes a potential issue with relying on the order returned by `planned_units()`.
> fix: Use peer relation to share peers addresses

- k8s/uv.lock
- machine/uv.lock
This is just a `uv lock --upgrade-package juju` on both charms.
Discovered while investigating https://github.com/canonical/vault-k8s-operator/issues/624
Updating this version should stop the failures on our CI.
> chore: update juju for potential authorize charm fix

- k8s/.vendored/vault-package/vault/vault_managers.py
- k8s/tests/unit/lib/test_vault_tls.py
- machine/.vendored/vault-package/vault/vault_managers.py
- vault-package/vault/vault_managers.py
Fixes #705 `set("abc")` will result in `{'a', 'b', 'c'}` this PR fixes that bug.
> fix: Add the CA to the set instead of converting the string itself to a set

- .github/workflows/trivy.yaml
Splits the trivy workflow into two separate jobs (one for k8s, one for machine charm) and tells it where to find the `uv.lock` file.
I haven't tested this yet, but once this is merged I can test fixes before merge (due to the `workflow_dispatch` addition)
> build(fix): configure uv.lock locations for trivy workflow
